### ISSUE TITLE
READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE

### ISSUE THREAD

**Issue by megoRU** [osk115/Qiwi4J#3]
QIWI такой QIWI...

https://github.com/osk115/Qiwi4J/blob/e58e3147880ef3128c3e851a44ff58b65c3f3f70/src/main/java/ru/osk/qiwi4j/Qiwi4JClient.java#L50-L68

```java
2023-06-20T12:50:04.078Z ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.NoSuchFieldError: READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.createContextual(EnumDeserializer.java:211) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:836) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:550) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:644) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:539) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:654) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4956) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4826) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740) ~[jackson-databind-2.15.0.jar!/:2.15.0]
        at ru.osk.qiwi4j.Qiwi4JClient.getBillInfo(Qiwi4JClient.java:63) ~[Qiwi4J-1.0.4.jar!/:na]
        at main.service.BillingService.lambda$billing$0(BillingService.java:46) ~[classes!/:0.0.1-SNAPSHOT]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
        at main.service.BillingService.billing(BillingService.java:39) ~[classes!/:0.0.1-SNAPSHOT]
        at main.config.BotStart.getStatus(BotStart.java:96) ~[classes!/:0.0.1-SNAPSHOT]
        at jdk.internal.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-6.0.9.jar!/:6.0.9]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.9.jar!/:6.0.9]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

```

**Comment by bulat5280** [comment]
У меня всё норм

**Comment by osk115** [comment]
Это ошибка на стороне [Jackson](https://github.com/FasterXML/jackson), в последней версии Qiwi4J используется версия `2.13.4.2`, возможно в вашем проекте есть другая версия `Jackson`?

```java
   /**
     * Override for <code>DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE</code>,
     * which allows unknown Enum values to be ignored and a predefined value specified through
     * {@link com.fasterxml.jackson.annotation.JsonEnumDefaultValue @JsonEnumDefaultValue} annotation.
     *
     * @since 2.15
     */
    READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE,
   ```

**Comment by megoRU** [comment]
Да я прошелся по брякам и понял что JSON возвращается корректный с QIWI. Сразу подумал про зависимости. Я недавно обновил Spring Boot `3.1.0` вот и-за него такая тема. на `3.0.7` полёт отличный
